name: 📸 Generate Photo Gallery

on:
  push:
    branches:
      - main
    paths:
      - 'photos/**'

  workflow_dispatch:

jobs:
  gallery:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate media index and video thumbnails
        run: |
          python3 ./.github/workflows/scripts/generate_photo_index.py

      - name: Commit generated gallery files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add _data/photos.json
          git add assets/gallery-thumbnails

          git diff --cached --quiet ||
            git commit -m "chore: update photo gallery"

          git push
